# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.c36cvcxv7nh5.sa-east-1.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin
