# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cntqvb6ccmij.sa-east-1.rds.amazonaws.com:3306/realmeet-db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: admin
